# Generated by Django 3.1.5 on 2021-03-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdatePrice',
        ),
    ]
