# Generated by Django 3.1.5 on 2021-03-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0002_delete_updateprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.FloatField(default=0)),
                ('selling_price', models.FloatField(default=0)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data1.stock')),
            ],
        ),
    ]
