# Generated by Django 3.1.5 on 2021-03-28 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0005_auto_20210328_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
