# Generated by Django 3.1.5 on 2021-03-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0006_item_date_recorded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock_item',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='updateprice',
            old_name='stock_item',
            new_name='stock',
        ),
    ]
