# Generated by Django 3.1.5 on 2021-03-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0010_auto_20210328_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprice',
            name='stock_item_code',
        ),
        migrations.AlterField(
            model_name='updateprice',
            name='item_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data1.stock'),
        ),
    ]
