# Generated by Django 3.1.5 on 2021-03-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0011_auto_20210328_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprice',
            name='id',
        ),
        migrations.AlterField(
            model_name='updateprice',
            name='item_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data1.stock'),
        ),
    ]
