# Generated by Django 3.1.5 on 2021-03-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0012_auto_20210328_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateprice',
            name='stock_item_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data1.stock'),
        ),
        migrations.AlterField(
            model_name='updateprice',
            name='item_code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
