# Generated by Django 3.1.5 on 2021-03-28 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0013_auto_20210328_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('sell_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_sold', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data1.stock')),
            ],
        ),
    ]
