# Generated by Django 3.1.5 on 2021-03-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0015_sellitem_sold_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='item_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
