# Generated by Django 3.1.5 on 2021-03-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0016_sellitem_item_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellitem',
            old_name='item_code',
            new_name='item',
        ),
    ]
