# Generated by Django 3.1.5 on 2021-03-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0020_restock_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restock',
            old_name='stock',
            new_name='stock_code',
        ),
        migrations.RemoveField(
            model_name='restock',
            name='item',
        ),
    ]
