# Generated by Django 3.1.5 on 2021-03-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0021_auto_20210331_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock',
            name='item_char',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restock',
            name='item_slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
