# Generated by Django 3.1.5 on 2021-03-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0022_auto_20210331_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restock',
        ),
    ]
