# Generated by Django 3.1.5 on 2021-03-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0026_restock_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restock',
            name='item_char',
        ),
        migrations.RemoveField(
            model_name='restock',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='restock',
            name='item_slug',
        ),
    ]
