# Generated by Django 3.1.5 on 2021-03-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0028_auto_20210331_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restock',
            old_name='stock_code',
            new_name='item_name',
        ),
    ]
