# Generated by Django 3.1.5 on 2021-03-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0030_auto_20210331_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdatePrice',
        ),
    ]
