# Generated by Django 3.1.5 on 2021-03-31 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0032_updateprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailItemSales',
            fields=[
                ('sales_number', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=200)),
                ('sales_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTotalSales',
            fields=[
                ('sales_date', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='sellitem',
            old_name='item_name',
            new_name='stock',
        ),
    ]
