# Generated by Django 3.1.5 on 2021-03-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0033_auto_20210401_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSales',
            fields=[
                ('sales_number', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=200)),
                ('total_sales', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='DailItemSales',
        ),
        migrations.AddField(
            model_name='dailytotalsales',
            name='item_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
