# Generated by Django 3.1.5 on 2021-03-31 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0034_auto_20210401_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytotalsales',
            name='sales_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dailytotalsales',
            name='sales_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
