# Generated by Django 3.1.5 on 2021-03-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0035_auto_20210401_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytotalsales',
            name='item_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailytotalsales',
            name='sales_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
