# Generated by Django 3.1.5 on 2021-04-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0038_auto_20210401_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='date_sold',
            field=models.DateField(auto_now_add=True),
        ),
    ]
