# Generated by Django 3.1.5 on 2021-04-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0040_auto_20210401_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellitem',
            name='date_sold',
        ),
    ]
